import type { Metadata } from "next";
import { Google_Sans_Flex } from "next/font/google";
import "./globals.scss";

const googleSansFlex = Google_Sans_Flex({
  variable: "--font-google-sans-flex",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "MicroSEL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${googleSansFlex.variable}`}>
        {children}
      </body>
    </html>
  );
}
